// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7DW1tdDT-5ubpZqN0wNoz2xN-IH3-0HQ',
    appId: '1:747248117420:web:4c71785b0b234d1ccf6109',
    messagingSenderId: '747248117420',
    projectId: 'flash-chat-d1847',
    authDomain: 'flash-chat-d1847.firebaseapp.com',
    storageBucket: 'flash-chat-d1847.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_UKlSlsK0DwEx5At10gc76iAZrftWc_g',
    appId: '1:747248117420:android:165833bafd7cac7acf6109',
    messagingSenderId: '747248117420',
    projectId: 'flash-chat-d1847',
    storageBucket: 'flash-chat-d1847.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeCUm3w6eBm8z4BMeaipa4FJNXEUCjIBs',
    appId: '1:747248117420:ios:5b2fa6e653a613abcf6109',
    messagingSenderId: '747248117420',
    projectId: 'flash-chat-d1847',
    storageBucket: 'flash-chat-d1847.firebasestorage.app',
    iosBundleId: 'com.ejejlee.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeCUm3w6eBm8z4BMeaipa4FJNXEUCjIBs',
    appId: '1:747248117420:ios:16192f3affb6f487cf6109',
    messagingSenderId: '747248117420',
    projectId: 'flash-chat-d1847',
    storageBucket: 'flash-chat-d1847.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7DW1tdDT-5ubpZqN0wNoz2xN-IH3-0HQ',
    appId: '1:747248117420:web:532e8d78cc5de87acf6109',
    messagingSenderId: '747248117420',
    projectId: 'flash-chat-d1847',
    authDomain: 'flash-chat-d1847.firebaseapp.com',
    storageBucket: 'flash-chat-d1847.firebasestorage.app',
  );
}
